// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://snfgnsiyieognthvpyto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNuZmduc2l5aWVvZ250aHZweXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyODMwOTAsImV4cCI6MjA2ODg1OTA5MH0.h1QMyDalwQp6ABPyoTeZ5OTy6uIXOe2mNzM1azexo1c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});